logging:
  file: logs/my.log
spring:
  profiles:
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1111
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 10MB
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6380
    # Redis服务器连接密码（默认为空）
    password: jabx2017_999
    # 连接超时时间（毫秒）
    timeout: 2000
  data:
    redis:
      repositories:
        enabled: false
server:
  port: 8280
  servlet:
    context-path: /shop
file:
  # 文件保存位置
  rootPath: /Users/liguanhuan/app/show/file
login:
# 不需要登录的请求
  no-check-url: ["/login.html", "/login", "/user/wxLogin"]
executor:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 100
  keepaliveSeconds: 60
  threadNamePrefix: MyAsyn-
# 微信支付相关
wechat:
  appId: 111
  secret: 111
  #商户账号appid
  mchAppid: 111
  #商户号
  mchid: 111
  #微信加密key
  key: 111
  #ip
  ip: 127.0.0.1
token:
  signKey: juan2019
  # 单位分
  expired: 30

# 京东相关
jd:
  serverUrl: "https://router.jd.com/api"
  accessToken:
  appKey: "***"
  appSecret: "***"
  sideId: "***"